# Dockerfile
FROM python:3.11-stretch
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /source
WORKDIR /source
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["main.py"]