# Dockerfile
FROM python:3.11
RUN apt-get update -y
# RUN apt-get install -y python-pip python-dev build-essential
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["main.py"]